FROM golang:1.25-alpine AS build

WORKDIR /app
COPY . /app

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./cmd/api

FROM alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /app
COPY --from=build /app/app /app/app
RUN chmod +x /app/app

EXPOSE 9091
CMD ["/app/app"]
