name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Vet
        run: go vet ./...

      - name: Run Tests
        run: go test ./... -v

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Build and deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          command_timeout: 10m
          script_stop: true
          script: |

            cd /root/license-api-git
            git pull

            docker build -t zeum-license-api:latest -f Dockerfile.prod .

            docker service update --force --image zeum-license-api:latest license-api-evyidx_api
